[book]
authors = ["Sandeep Kunkunuru"]
language = "en"
multilingual = false
src = "src"
title = "Building Samyama: The Architecture of a Modern Rust Graph Database"

[output.html]
git-repository-url = "https://github.com/Madhulatha-Sandeep/samyama-graph"
edit-url-template = "https://github.com/Madhulatha-Sandeep/samyama-graph-book/edit/main/{path}"
